
post_install() {

cat << EOF
  -------------------------------------------------------------
   To enable for systemd, do 'systemctl enable agnclientd'
   The daemon must be running for ATT VPN Client to fucntion
   do 'systemctl start agnclientd' and then launch the GUI
  -------------------------------------------------------------
EOF

 chmod 777 /var/agns/fifo/*

}

post_upgrade() {
    post_install $1
}
